### ISSUE TITLE
Install for Mysql 5.6

### ISSUE THREAD

**Issue by Dashing-Nelson** [nonbeing/mysqlclient-python3-aws-lambda#1]
Hello,
first of all great initiative. This is something i always dreamed of having on lambda. Could you guide me on which libmysqlclient.so version i would need for 5.6.41. i tried the official one but it fails. Any help will be appreciated

**Comment by nonbeing** [comment]
Hi - thanks for trying this project out!

To answer your question: you need `libmysqlclient.so.18` for MySQL 5.6.x that is obtained from the `mysql-community-common.x86_64 0:5.6.49-2.el7` yum package.

However, based on your message, I have made the changes necessary for building and packaging the AWS Lambda layer for MySQL 5.6 (and Python 3.8) in the [mysql-5.6 branch](https://github.com/nonbeing/mysqlclient-python3-aws-lambda/tree/mysql-5.6) in this GitHub repo. It has been tested and works fine.

Also the final `layer.zip` file that you need to upload to AWS Lambda to create your layer (for MySql 5.6) is also [directly available in this repo itself in the mysql-5.6 branch](https://github.com/nonbeing/mysqlclient-python3-aws-lambda/tree/mysql-5.6/build_output). I have tested this in an AWS Lambda function, and it is working just fine with Python 3.8

If you want to build your own `layer.zip` from scratch, that's easy too. Just clone this repo, `git checkout` the `mysql-5.6` branch and run the `./build.sh` script (provided you have Docker installed and running beforehand). It will do the needful and you will get the required `layer.zip` file in the `build_ouptut` directory.

Let me know if this works for you and if there's anything else I can help with.

**Comment by Dashing-Nelson** [comment]
Sure will try and let you know. Thanks

**Comment by Dashing-Nelson** [comment]
Seems to give an access denied error.
I currently have aws rds mysql version 5.6.41
connects fine with pymysql. So i am sure there is a problem with the connector file.
Also the db has ssl enabled.
`            engine = _mysql.connect(host=host,
                                    user=user,
                                    passwd=pwd,
                                    db=db,
                                    ssl={'ssl': {'ca': environ["ssl_ca"]}})`

**Comment by nonbeing** [comment]
I ran the following test code in a Lambda function. The Lambda function is using the Lambda layer that I created and shared above for MySQL 5.6, and I tested it against an RDS MySQL DB running MySQL 5.6.41:

```
from MySQLdb import _mysql

def lambda_handler(event, context):
    db=_mysql.connect(host="database-1.cywusodsboh0.us-east-1.rds.amazonaws.com",port=3306,user="admin",passwd="..................",db="test")
    db.query("""SHOW DATABASES;""")
    r=db.store_result()
    print(r.fetch_row(0))
```

As you can see from the resultant screenshot here, the code is not only connecting to the DB, but it the query is also executing just fine:
![lambda-layer-working](https://i.imgur.com/FLujNvH.png)



The purpose of the AWS Lambda layer is just to ensure that you can `import MySQLdb` without any error in your AWS Lambda Function as explained in the README.

Once the Lambda Layer has got you to the stage where `import MySQLdb` is working, the project has accomplished its purpose :)

The following are out of scope of this project:
- connection errors
- the lambda function configuration (is it in the right VPC, does it have the right security groups, the right subnets, the right IAM role etc etc) 
- the proper DB config
- proper `_mysql ` usage 

There can be several reasons why the connection is not working - incorrect connString, VPC config, SGs, etc. Without further information it's not easy to pinpoint the cause of failure to the Lambda layer itself. 

We are using the Lambda `mysqlclient` layer in our production environment and it has been performing flawlessly for months now. The Lambda layer is not the cause of your connection errors :)

**Comment by nonbeing** [comment]
Also just to prove that my RDS instance is actually running MySQL `5.6.41`, here's a screenshot:

![testdb](https://i.imgur.com/HjrI4y3.png)

**Comment by Dashing-Nelson** [comment]
This is very strange. Do you think having SSL enabled to have something to do with it?

**Comment by nonbeing** [comment]
Yes, it's a possibility. You will have to troubleshoot the connection issues - as hinted at earlier, there can literally be dozens of reasons why it's not working for you, and unfortunately I can't do this for you. 

I can assure you that the Lambda layer for `mysqlclient` is not one of the reasons that you are getting connection errors - As shown above, it's working fine even with MySQL 5.6.41 :)

**Comment by Dashing-Nelson** [comment]
i can confirm it does work. SSL was the issue
```
                _mysql.connect(host=values['endpoint'],
                               user=values['username'],
                               passwd=values['password'],
                               db=values['db'],
                               ssl={'ca': ssl_ca_name()})
```
this is the correct syntax

**Comment by Dashing-Nelson** [comment]
closing this. Thanks and keep up the good work. Really helpful.

**Comment by nonbeing** [comment]
Great! Thanks for the update, and glad it is working for you now 👍 
Thanks also for sharing the solution that works with SSL.
If you found this project useful consider giving it a star here on GitHub. Cheers!

**Comment by Dashing-Nelson** [comment]
already did.... Great work.....
