### ISSUE TITLE
MySQL did not work but the bundled image works still

### ISSUE THREAD

**Issue by rezazamani** [nonbeing/mysqlclient-python3-aws-lambda#10]
Hi,

First off, thank you so much for building this repo! This saved a lot of time from me and unblocked me when I needed it most!

I tried building the image using the repo and everything seemed ok (I am using MacOS 13.0.1), however, the images that I ended up creating never passed the MySQL test on Lambda. It does work certainly for other packages (e.g., `requests` package). The bundled binary of the image included in the repo still works btw and that worked great. 

Is there any interest in automating more of the infra building and testing using Terraform? I might be able to help.

**Comment by nonbeing** [comment]
Hi there - first of all, sorry for the delayed response. My life has been through the wringer recently and I haven't been active as much as I'd like.

Glad this repo could be of some use to you.

If you're able to build pure-python libraries (that don't contain any platform-specific binaries) such as `requests`, but aren't able to do the same for python libraries that contain platform-specific binaries (e.g. `mysqlclient`), then I would first recommend double-checking your Docker setup. Then I would suggest carefully going through the steps in the README again - the instructions work for many people and have been tested many times. 

Thanks for the offer to help building out any automation - I'll definitely get in touch when we get to that point 🙂

Please let me know if you're still having problems building `mysqlclient` or if we can close this GH issue.

**Comment by cheitovilla** [comment]
Hello, first off, thanks for the repo! i have some issues: 

Response
{
  "errorMessage": "name '_mysql' is not defined",
  "errorType": "NameError",
  "stackTrace": [
    "  File \"/var/lang/lib/python3.8/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n",
    "  File \"/var/lang/lib/python3.8/imp.py\", line 171, in load_source\n    module = _load(spec)\n",
    "  File \"<frozen importlib._bootstrap>\", line 702, in _load\n",
    "  File \"<frozen importlib._bootstrap>\", line 671, in _load_unlocked\n",
    "  File \"<frozen importlib._bootstrap_external>\", line 843, in exec_module\n",
    "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
    "  File \"/var/task/lambda_function.py\", line 2, in <module>\n    import MySQLdb\n",
    "  File \"/opt/python/MySQLdb/__init__.py\", line 24, in <module>\n    version_info, _mysql.version_info, _mysql.__file__\n"
  ]
}


Do you have any idea what is my problem? im using python 3.8 in aws lambda.

**Comment by nonbeing** [comment]
@cheitovilla at first glance this looks like Python can't find the `libmysqlclient.so` binary in the MySQL package.

Are you using the bundled `layer.zip` file or generating your own?

**Comment by cheitovilla** [comment]
thanks for quickly answer, I'm using the layer.zip file, I just renamed it to MySQLdb.zip, maybe could be the name? 

Best.

**Comment by cheitovilla** [comment]
@nonbeing hello again, the name wasnt.  i dont know what is my issues u,u

**Comment by nonbeing** [comment]
Are you using ARM-based Lambda function? That won't work. Because the layer.zip files contain `.so` files compiled for x86.

**Comment by cheitovilla** [comment]
thank you for your response. The error I had when creating the .zip was that I didn't name the python folder.

**Comment by nonbeing** [comment]
Thanks for the update. Closing issue as resolved.
