### ISSUE TITLE
Returning bytes instead of strings  

### ISSUE THREAD

**Issue by yousefjnm** [nonbeing/mysqlclient-python3-aws-lambda#2]
Hello,

First of all, let me thank you so much for this great project. It's really helpful.

I am facing one problem though. it's returning all bytes instead of strings. looping through the query huge output to decode everything to strings takes relatively long time. Is there anyway to make it return strings instead of bytes? 

I have read somewhere that downgrading mysqlclient to 1.3.9 would make it return strings, have you tried that?

Again, thank you so much!

**Comment by nonbeing** [comment]
Hi there. Glad you found this project useful  👍

I don't recommend using `mysqlclient` directly for raw queries (I guess that's what you're doing). You can use a more user-friendly layer on top of `mysqlclient` such as  [SQLAlchemy](https://www.sqlalchemy.org/) which should solve your problems.

SQLAlchemy is a mature, well-documented and widely-used Python package. Among other hallmarks, SQLAlchemy is the default and only "engine" that `pandas` uses to connect to SQL databases.

In my own projects, I use SQLAlchemy for DDL and DML queries and also as a powerful ORM layer between my apps and MySQL. SQLAlchemy uses `mysqlclient` as the default driver to connect to a MySQL database. It can [also optionally use `pymysql` or other drivers](https://docs.sqlalchemy.org/en/14/core/engines.html#mysql).

I use SQLAlchemy v1.4.x with the `mysqlclient` (v2.0.1 to v2.0.3) driver and I've never encountered the issues you mentioned - you get direct Python lists/dictionaries or ORM-defined objects back which are far easier to use.

**Comment by yousefjnm** [comment]
Thank you so much for your response.

SO my of my queries return huge outputs so I was trying to find the library that would make my API as fast as possible. I really like `mysqlclient` speed but the only thing is that I have to decode all items which takes a bit of time but it's still better/faster than anything else I have tried so far. 

Does using `SQLAlchemy` on top affect the speed? does it make the return time a bit slower?

Again, thank you so much

**Comment by nonbeing** [comment]
I don't think SqlAlchemy will slow down your app much, but only you can make that call.

You could always benchmark both approaches for a sample use case, and then decide if SqlAlchemy is performant enough for you.

All the best!

**Comment by yousefjnm** [comment]
Thank you so much!
