### ISSUE TITLE
No layer.zip file

### ISSUE THREAD

**Issue by SunainaDG** [nonbeing/mysqlclient-python3-aws-lambda#3]
I cant find the layer.zip file in your repo.

**Comment by nonbeing** [comment]
You're right, it's missing on `master` branch. But the `layer.zip` is there on the `mysql-5.6` branch.

I'll add the missing `build_output/layer.zip` for `master` branch in the next few mins.

**Comment by nonbeing** [comment]
@SunainaDG, the `layer.zip` file is now available in the `build_output` directory.

What version of MySQL do you need it for?

**Comment by nonbeing** [comment]
@SunainaDG : the `layer.zip` file is now available. If this meets your requirements, can this issue be closed now?

**Comment by SunainaDG** [comment]
@nonbeing : I need it for 8

**Comment by SunainaDG** [comment]
Hey you think there is a way to build a similar package for AWS glue?

**Comment by nonbeing** [comment]
@SunainaDG the layer.zip file is available for MySQL 8 in master branch in the `build_output` directory as shown here:

![image](https://user-images.githubusercontent.com/897313/134505597-75d89a59-43b6-47a0-bc4e-30c2b4b178ee.png)

I'm not aware of how to use this for AWS glue, this is meant for AWS Lambda Layers.

**Comment by SunainaDG** [comment]
Ah no yes I know its for Lambda, just thought of asking in case you might know.

Anyway thanks for the zip. :)

**Comment by nonbeing** [comment]
Closing this issue.
