### ISSUE TITLE
ImportError: No module named _mysql

### ISSUE THREAD

**Issue by dragonballa** [nonbeing/mysqlclient-python3-aws-lambda#5]
so I tried uploading the layer.zip to aws lambda layer and it still complains that it cannot find the no module named _mysql

could this be because I am on a mac?

**Comment by smatsumt** [comment]
I encountered same issue. I used Python3.9.
Current master layer.zip is for Python3.8, and it seems that it does not work in Python3.9.

I've created PR which creates mysqliclient lambda layer for Python 3.9.

If you are in harry, you can use it from my forked repository.

https://github.com/smatsumt/mysqlclient-python3-aws-lambda/tree/master/build_output

**Comment by nonbeing** [comment]
@dragonballa I have now merged in the PRs from @smatsumt 
The new `layer.zip` on `master` branch works with Python 3.9 now - please see if it works for you.

**Comment by nonbeing** [comment]
Closing this issue because there is a solution to this problem now available on the `master` branch, and also no response from the issue reporter for 5 months now.
